services:
  mongo:
    image: mongo:latest
    container_name: mongodb_ttag
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ttag_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: db_tags
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

#  app:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    container_name: ttag
#    depends_on:
#      - mongo
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    volumes:
#      - ../app:/srv/app
#      - ../var:/srv/var
#      - ../templates:/srv/templates
#    logging:
#      driver: json-file
#      options:
#        max-size: "10m"
#        max-file: "5"

volumes:
  ttag_mongo_data:
